In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df = pd.read_csv(r'C:\Users\adity\Downloads\Dyashin Technosoft DS Internship\Datasets\US_births_2000-2014_SSA.csv')
df

      year  month  date_of_month  day_of_week  births        date
0     2000      1              1            6    9083  01/01/2000
1     2000      1              2            7    8006  01/02/2000
2     2000      1              3            1   11363  01/03/2000
3     2000      1              4            2   13032  01/04/2000
4     2000      1              5            3   12558  01/05/2000
...    ...    ...            ...          ...     ...         ...
5474  2014     12             27            6    8656  12/27/2014
5475  2014     12             28            7    7724  12/28/2014
5476  2014     12             29            1   12811  12/29/2014
5477  2014     12             30            2   13634  12/30/2014
5478  2014     12             31            3   11990  12/31/2014

[5479 rows x 6 columns]

In [3]:
df.shape

(5479, 6)

In [5]:
df.head(10)

   year  month  date_of_month  day_of_week  births        date
0  2000      1              1            6    9083  01/01/2000
1  2000      1              2            7    8006  01/02/2000
2  2000      1              3            1   11363  01/03/2000
3  2000      1              4            2   13032  01/04/2000
4  2000      1              5            3   12558  01/05/2000
5  2000      1              6            4   12466  01/06/2000
6  2000      1              7            5   12516  01/07/2000
7  2000      1              8            6    8934  01/08/2000
8  2000      1              9            7    7949  01/09/2000
9  2000      1             10            1   11668  01/10/2000

In [7]:
df.tail(10)

      year  month  date_of_month  day_of_week  births        date
5469  2014     12             22            1   12799  12/22/2014
5470  2014     12             23            2   12604  12/23/2014
5471  2014     12             24            3    9308  12/24/2014
5472  2014     12             25            4    6749  12/25/2014
5473  2014     12             26            5   10386  12/26/2014
5474  2014     12             27            6    8656  12/27/2014
5475  2014     12             28            7    7724  12/28/2014
5476  2014     12             29            1   12811  12/29/2014
5477  2014     12             30            2   13634  12/30/2014
5478  2014     12             31            3   11990  12/31/2014

In [8]:
df.isna().sum()

year             0
month            0
date_of_month    0
day_of_week      0
births           0
date             0
dtype: int64

In [9]:
df.duplicated().sum()

0

In [ ]:
# Convert data types safely
numeric_columns = ['year', 'month', 'date_of_month', 'day_of_week', 'births']
for col in numeric_columns:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')

In [13]:
# Handle missing numeric values using median
for col in numeric_columns:
    if col in df.columns:
        df[col] = df[col].fillna(df[col].median())

In [14]:
# Create proper datetime column using correct parameter names
if all(col in df.columns for col in ['year', 'month', 'date_of_month']):
    df['full_date'] = pd.to_datetime({
        'year': df['year'],
        'month': df['month'],
        'day': df['date_of_month']
    }, errors='coerce')

In [15]:
# Add weekday name and weekend flag
if 'full_date' in df.columns:
    df['weekday_name'] = df['full_date'].dt.day_name()
    df['is_weekend'] = df['weekday_name'].isin(['Saturday', 'Sunday']).astype(int)

In [16]:
df

,year,month,date_of_month,day_of_week,births,date,full_date,weekday_name,is_weekend
0,2000,1,1,6,9083,01/01/2000,2000-01-01,Saturday,1
1,2000,1,2,7,8006,01/02/2000,2000-01-02,Sunday,1
2,2000,1,3,1,11363,01/03/2000,2000-01-03,Monday,0
3,2000,1,4,2,13032,01/04/2000,2000-01-04,Tuesday,0
4,2000,1,5,3,12558,01/05/2000,2000-01-05,Wednesday,0
...,...,...,...,...,...,...,...,...,...
5474,2014,12,27,6,8656,12/27/2014,2014-12-27,Saturday,1
5475,2014,12,28,7,7724,12/28/2014,2014-12-28,Sunday,1
5476,2014,12,29,1,12811,12/29/2014,2014-12-29,Monday,0
5477,2014,12,30,2,13634,12/30/2014,2014-12-30,Tuesday,0
5478,2014,12,31,3,11990,12/31/2014,2014-12-31,Wednesday,0